import { sql } from 'drizzle-orm';
import { timestamp, uuid } from 'drizzle-orm/pg-core';

/**
 * Standard ID column. UUID primary key, generated by Postgres
 * (`gen_random_uuid()`). Per CLAUDE_CODE.md §8 schema rule #1 +
 * clarifications.md Q1: every table uses this unless explicitly otherwise.
 */
export const idColumn = () =>
  uuid('id').primaryKey().default(sql`gen_random_uuid()`);

/** Standard created_at. CLAUDE_CODE.md §8 rule #2. */
export const createdAt = () =>
  timestamp('created_at', { withTimezone: true }).notNull().defaultNow();

/** Standard updated_at. CLAUDE_CODE.md §8 rule #3 (trigger added separately if used). */
export const updatedAt = () =>
  timestamp('updated_at', { withTimezone: true }).notNull().defaultNow();
